// Treści modułu „Czaszka”. Plik można edytować bez znajomości reszty kodu.
// Klucze kości (frontal, parietal…) odpowiadają nazwom siatek w models/pakiety/czaszka-*.pak (tools/czaszka.py),
// klucze części — punktom w landmarks-czaszka.js.
// WERSJA ROBOCZA: opisy wymagają weryfikacji przez nauczyciela anatomii.

export const SKULL_REGIONS = {
  NC: { name: 'Mózgoczaszka', latin: 'Neurocranium', count: '8 kości', curve: 'Czaszka',
        text: 'Otacza i chroni mózg. Tworzą ją kość czołowa, dwie ciemieniowe, potyliczna, dwie skroniowe, klinowa i sitowa. Kości sklepienia łączą się szwami — u noworodka między nimi są ciemiączka, które zarastają w pierwszych latach życia.' },
  VC: { name: 'Twarzoczaszka', latin: 'Viscerocranium', count: '14 kości w modelu', curve: 'Czaszka',
        text: 'Szkielet twarzy: oczodoły, jama nosowa, jama ustna. W modelu: szczęki, kości jarzmowe, nosowe, łzowe, podniebienne, małżowiny nosowe dolne, lemiesz i żuchwa. Kości gnykowej nie pokazano. Żuchwa to jedyna ruchoma kość czaszki — łączy się z kością skroniową w stawie skroniowo-żuchwowym.' },
};

// Kości: name, latin, short (skrót w quizie), features (cechy), massage (dla masażysty), muscles (przyczepy)
export const SKULL_PARTS = {
  frontal: {
    name: 'Kość czołowa', latin: 'Os frontale', short: 'Os frontale',
    features: [
      'Nieparzysta. Tworzy czoło, przednią część sklepienia czaszki i górne ściany oczodołów.',
      'Łuska czołowa przechodzi w dół w brzegi nadoczodołowe i łuki brwiowe; między łukami leży gładzizna.',
      'W jej wnętrzu, nad nasadą nosa, jest zatoka czołowa — jedna z zatok przynosowych.',
      'Z kośćmi ciemieniowymi łączy się szwem wieńcowym.',
    ],
    massage: 'Czoło masujemy od środka (gładzizny) na boki, wzdłuż łuków brwiowych. We wcięciu nadoczodołowym wychodzi nerw nadoczodołowy (gałąź nerwu trójdzielnego) — ucisk w tym miejscu tylko delikatny.',
    muscles: 'Marszczący brwi (część nosowa i łuk brwiowy), okrężny oka (część oczodołowa), skroniowy (dół skroniowy poniżej kresy skroniowej). Brzusiec czołowy mięśnia potyliczno-czołowego nie przyczepia się do kości — wplata się w skórę brwi.',
  },
  parietal: {
    name: 'Kość ciemieniowa', latin: 'Os parietale', short: 'Os parietale',
    features: [
      'Parzysta. Dwie kości ciemieniowe tworzą większą część sklepienia i boczne ściany czaszki.',
      'Łączą się ze sobą szwem strzałkowym, z kością czołową — wieńcowym, z potyliczną — węgłowym, ze skroniową — łuskowym.',
      'Najbardziej wypukłe miejsce to guz ciemieniowy. Poniżej biegnie łukowato kresa skroniowa.',
    ],
    massage: 'Masaż skóry owłosionej głowy przesuwa czepiec ścięgnisty po kościach ciemieniowych. Szwy są niewyczuwalne u dorosłych; u niemowląt w miejscu styku szwów leżą ciemiączka — nie uciskamy.',
    muscles: 'Skroniowy (poniżej kresy skroniowej dolnej), powięź skroniowa (kresa skroniowa górna). Na sklepieniu leży czepiec ścięgnisty mięśnia potyliczno-czołowego.',
  },
  occipital: {
    name: 'Kość potyliczna', latin: 'Os occipitale', short: 'Os occipitale',
    features: [
      'Nieparzysta. Tworzy tył i dużą część podstawy czaszki.',
      'Ma otwór wielki — przez niego rdzeń przedłużony przechodzi w rdzeń kręgowy.',
      'Po bokach otworu leżą kłykcie potyliczne — łączą się z kręgiem szczytowym (C1) w stawie szczytowo-potylicznym (ruch „tak”).',
      'Na zewnętrznej powierzchni łuski: guzowatość potyliczna zewnętrzna i kresy karkowe — przyczepy mięśni karku.',
    ],
    massage: 'Guzowatość potyliczna zewnętrzna to górny punkt orientacyjny karku. Wzdłuż kresy karkowej górnej rozcieramy przyczepy mięśni karku. Pod potylicą leżą mięśnie podpotyliczne i nerw potyliczny większy — ucisk umiarkowany.',
    muscles: 'Czworoboczny (kresa karkowa górna i guzowatość), płatowaty głowy i mostkowo-obojczykowo-sutkowy (boczna część kresy karkowej górnej), półkolcowy głowy (między kresami karkowymi), prosty tylny większy i mniejszy głowy, skośny górny głowy, brzusiec potyliczny mięśnia potyliczno-czołowego.',
  },
  temporal: {
    name: 'Kość skroniowa', latin: 'Os temporale', short: 'Os temporale',
    features: [
      'Parzysta. Tworzy boczną ścianę i część podstawy czaszki; w jej wnętrzu leży narząd słuchu i równowagi.',
      'Części: łuska (z wyrostkiem jarzmowym), część bębenkowa (z otworem słuchowym zewnętrznym), część skalista (z wyrostkiem sutkowatym).',
      'Wyrostek jarzmowy razem z wyrostkiem skroniowym kości jarzmowej tworzy łuk jarzmowy.',
      'W dole żuchwowym tworzy z głową żuchwy staw skroniowo-żuchwowy.',
    ],
    massage: 'Wyrostek sutkowaty wyczuwamy za małżowiną uszną — to przyczep mięśnia mostkowo-obojczykowo-sutkowego. Przed uchem, przy otwieraniu ust, czuć ruch głowy żuchwy w stawie skroniowo-żuchwowym. Mięsień skroniowy masujemy nad łukiem jarzmowym.',
    muscles: 'Mostkowo-obojczykowo-sutkowy, płatowaty głowy, najdłuższy głowy (wyrostek sutkowaty), dwubrzuścowy — brzusiec tylny (wcięcie sutkowe), skroniowy (łuska), żwacz (łuk jarzmowy), rylcowo-gnykowy (wyrostek rylcowaty).',
  },
  sphenoid: {
    name: 'Kość klinowa', latin: 'Os sphenoidale', short: 'Os sphenoidale',
    features: [
      'Nieparzysta, w środku podstawy czaszki — łączy się ze wszystkimi kośćmi mózgoczaszki.',
      'Kształtem przypomina motyla: trzon z siodłem tureckim (leży w nim przysadka), skrzydła większe i mniejsze, wyrostki skrzydłowate.',
      'Skrzydło większe widać z boku czaszki, w skroni, za oczodołem.',
      'W trzonie leży zatoka klinowa.',
    ],
    massage: 'Pterion (w skroni) to miejsce zetknięcia kości czołowej, ciemieniowej, skroniowej i skrzydła większego klinowej — najcieńsza część bocznej ściany czaszki, pod nią biegnie tętnica oponowa środkowa. Bez silnego, punktowego ucisku.',
    muscles: 'Skroniowy (skrzydło większe), skrzydłowe boczny i przyśrodkowy (wyrostek skrzydłowaty), mięśnie proste gałki ocznej (wokół kanału wzrokowego).',
  },
  ethmoid: {
    name: 'Kość sitowa', latin: 'Os ethmoidale', short: 'Os ethmoidale',
    features: [
      'Nieparzysta, lekka, leży między oczodołami — tworzy górną część przegrody i ścian jamy nosowej.',
      'Blaszka sitowa ma liczne otworki, przez które przechodzą włókna nerwu węchowego.',
      'Błędnik sitowy zawiera komórki sitowe — część zatok przynosowych.',
    ],
    massage: 'Niewyczuwalna. Przy zapaleniu komórek sitowych ból bywa odczuwany między oczami, u nasady nosa.',
    muscles: 'Brak przyczepów mięśni szkieletowych. Do grzebienia koguciego przyczepia się sierp mózgu (opona twarda).',
  },
  nasal: {
    name: 'Kość nosowa', latin: 'Os nasale', short: 'Os nasale',
    features: [
      'Parzysta, mała, podłużna. Obie kości nosowe tworzą kostny grzbiet nosa.',
      'U góry łączą się z kością czołową — miejsce styku w linii środkowej to nasion.',
      'Niżej grzbiet nosa przechodzi w chrząstki nosa.',
    ],
    massage: 'Wyczuwalna jako twarda górna część grzbietu nosa. Masaż nosa wykonujemy delikatnie, wzdłuż jego boków.',
    muscles: 'Mięsień podłużny (procerus) — zaczyna się na grzbiecie nosa.',
  },
  lacrimal: {
    name: 'Kość łzowa', latin: 'Os lacrimale', short: 'Os lacrimale',
    features: [
      'Parzysta, najmniejsza kość twarzoczaszki. Leży w przyśrodkowej ścianie oczodołu.',
      'Razem z wyrostkiem czołowym szczęki tworzy dół woreczka łzowego, z którego kanał nosowo-łzowy odprowadza łzy do nosa.',
    ],
    massage: 'Niewyczuwalna. W przyśrodkowym kącie oka leży woreczek łzowy — nie uciskamy.',
    muscles: 'Okrężny oka (część łzowa).',
  },
  zygomatic: {
    name: 'Kość jarzmowa', latin: 'Os zygomaticum', short: 'Os zygomaticum',
    features: [
      'Parzysta. Tworzy wyniosłość policzka oraz boczny i dolny brzeg oczodołu.',
      'Wyrostek skroniowy z wyrostkiem jarzmowym kości skroniowej tworzy łuk jarzmowy.',
      'Wyrostek czołowy łączy się z kością czołową w bocznym brzegu oczodołu.',
    ],
    massage: 'Wyniosłość jarzmowa to najwyższy punkt policzka. Od dolnego brzegu łuku jarzmowego zaczyna się żwacz — wyczuwamy go, gdy pacjent zaciska zęby.',
    muscles: 'Żwacz (dolny brzeg łuku jarzmowego), jarzmowy większy i mniejszy. Do górnego brzegu łuku jarzmowego przyczepia się powięź skroniowa.',
  },
  maxilla: {
    name: 'Szczęka', latin: 'Maxilla', short: 'Maxilla',
    features: [
      'Parzysta. Obie szczęki tworzą środek twarzy: dno oczodołów, boczne ściany jamy nosowej i większą część podniebienia twardego.',
      'Wyrostek zębodołowy niesie zęby górne.',
      'W trzonie leży zatoka szczękowa — największa z zatok przynosowych.',
      'Pod dolnym brzegiem oczodołu leży otwór podoczodołowy.',
    ],
    massage: 'Otwór podoczodołowy (ok. 1 cm pod dolnym brzegiem oczodołu) to ujście nerwu podoczodołowego (gałąź nerwu trójdzielnego) — punkt wrażliwy, uciskamy delikatnie. Okolica nad zatoką szczękową bywa tkliwa przy jej zapaleniu.',
    muscles: 'Dźwigacz wargi górnej, dźwigacz kąta ust, okrężny oka (wyrostek czołowy), nosowy, policzkowy (wyrostek zębodołowy przy zębach trzonowych), żwacz (wyrostek jarzmowy, razem z łukiem jarzmowym).',
  },
  mandible: {
    name: 'Żuchwa', latin: 'Mandibula', short: 'Mandibula',
    features: [
      'Nieparzysta, największa i najmocniejsza kość twarzy; jedyna ruchoma kość czaszki.',
      'Trzon w kształcie podkowy przechodzi w kącie żuchwy w gałęzie.',
      'Gałąź kończy się wyrostkiem kłykciowym (głowa żuchwy — staw skroniowo-żuchwowy) i wyrostkiem dziobiastym (przyczep mięśnia skroniowego).',
      'Część zębodołowa niesie zęby dolne; z przodu trzonu są otwory bródkowe.',
    ],
    massage: 'Kąt i dolny brzeg żuchwy to ważne punkty orientacyjne — pod trzonem leżą węzły chłonne podżuchwowe. Żwacz masujemy na bocznej powierzchni gałęzi. Głowę żuchwy wyczuwamy przed uchem przy otwieraniu ust.',
    muscles: 'Żwacz (kąt i boczna powierzchnia gałęzi), skrzydłowy przyśrodkowy (wewnętrzna powierzchnia kąta), skroniowy (wyrostek dziobiasty), skrzydłowy boczny (wyrostek kłykciowy), dwubrzuścowy (brzusiec przedni), żuchwowo-gnykowy, bródkowo-gnykowy, obniżacze wargi dolnej i kąta ust, bródkowy, policzkowy, mięsień szeroki szyi (dolny brzeg).',
  },
  vomer: {
    name: 'Lemiesz', latin: 'Vomer', short: 'Vomer',
    features: [
      'Nieparzysta, cienka blaszka w linii środkowej — tylna i dolna część kostnej przegrody nosa.',
      'Razem z blaszką pionową kości sitowej i chrząstką przegrody tworzy przegrodę nosa.',
    ],
    massage: 'Niewyczuwalny — leży wewnątrz jamy nosowej.',
    muscles: 'Brak przyczepów mięśni.',
  },
  palatine: {
    name: 'Kość podniebienna', latin: 'Os palatinum', short: 'Os palatinum',
    features: [
      'Parzysta, w kształcie litery L, leży za szczęką.',
      'Blaszka pozioma tworzy tylną część podniebienia twardego, blaszka pionowa — część bocznej ściany jamy nosowej.',
    ],
    massage: 'Niewyczuwalna przez skórę.',
    muscles: 'Do tylnego brzegu blaszki poziomej przyczepia się rozcięgno podniebienia miękkiego.',
  },
  concha: {
    name: 'Małżowina nosowa dolna', latin: 'Concha nasalis inferior', short: 'Concha nasalis inf.',
    features: [
      'Parzysta, zwinięta blaszka kostna na bocznej ścianie jamy nosowej.',
      'Pod nią leży przewód nosowy dolny — uchodzi do niego kanał nosowo-łzowy.',
      'Małżowiny górna i środkowa należą do kości sitowej.',
    ],
    massage: 'Niewyczuwalna — leży wewnątrz jamy nosowej.',
    muscles: 'Brak przyczepów mięśni.',
  },
  teeth: {
    name: 'Zęby', latin: 'Dentes', short: 'Dentes',
    features: [
      'Uzębienie stałe dorosłego to 32 zęby: w każdej ćwiartce 2 siekacze, kieł, 2 zęby przedtrzonowe i 3 trzonowe.',
      'W modelu jest 28 zębów — bez trzecich zębów trzonowych (zębów mądrości).',
      'Zęby górne tkwią w wyrostku zębodołowym szczęki, dolne — w części zębodołowej żuchwy.',
    ],
    massage: 'Przy masażu twarzy i żwacza pamiętaj o napięciu mięśni przy zaciskaniu zębów (bruksizm) — żwacz jest wtedy wyraźnie wyczuwalny i często tkliwy.',
    muscles: 'Zęby nie są przyczepem mięśni.',
  },
};

// Części kości (etykiety na modelu). palp: wyczuwalne pod palcami (czarna kropka); pair: parzyste [lewa, prawa].
export const SKULL_LABELS = {
  frontal: {
    squama:        { name: 'Łuska czołowa', latin: 'squama frontalis', palp: true,
                     def: 'Duża, płaska część tworząca czoło i przód sklepienia czaszki.' },
    tuber:         { name: 'Guz czołowy', latin: 'tuber frontale', palp: true, pair: true,
                     def: 'Najbardziej wypukłe miejsce czoła po każdej stronie, kilka centymetrów nad łukiem brwiowym.' },
    glabella:      { name: 'Gładzizna', latin: 'glabella', palp: true,
                     def: 'Płaskie miejsce między łukami brwiowymi, nad nasadą nosa.' },
    arcus:         { name: 'Łuk brwiowy', latin: 'arcus superciliaris', palp: true, pair: true,
                     def: 'Wał kostny nad brzegiem oczodołu, pod brwią. Bardziej wydatny u mężczyzn.' },
    margo_so:      { name: 'Brzeg nadoczodołowy', latin: 'margo supraorbitalis', palp: true, pair: true,
                     def: 'Górny brzeg oczodołu — dobrze wyczuwalna, ostra krawędź pod brwią.' },
    incisura_so:   { name: 'Wcięcie nadoczodołowe', latin: 'incisura (foramen) supraorbitalis', palp: true, pair: true,
                     def: 'Wcięcie (czasem otwór) w przyśrodkowej części brzegu nadoczodołowego. Wychodzą tędy nerw i naczynia nadoczodołowe.' },
    zyg_proc:      { name: 'Wyrostek jarzmowy kości czołowej', latin: 'processus zygomaticus ossis frontalis', palp: true, pair: true,
                     def: 'Boczny koniec brzegu nadoczodołowego. Łączy się z kością jarzmową w bocznym brzegu oczodołu.' },
    temporal_line: { name: 'Kresa skroniowa', latin: 'linea temporalis', palp: true, pair: true, line: 'temporal_line',
                     def: 'Łukowata linia zaczynająca się za wyrostkiem jarzmowym i biegnąca na kość ciemieniową. Ogranicza od góry dół skroniowy — do niej sięga mięsień skroniowy i jego powięź.' },
    coronal:       { name: 'Szew wieńcowy', latin: 'sutura coronalis', palp: false, pair: true, line: 'coronal',
                     def: 'Szew między kością czołową a kośćmi ciemieniowymi. Biegnie w poprzek sklepienia, od skroni do skroni.' },
    sinus:         { name: 'Zatoka czołowa', latin: 'sinus frontalis', palp: false,
                     def: 'Przestrzeń powietrzna w kości za gładzizną i łukami brwiowymi. Uchodzi do jamy nosowej.' },
  },
  parietal: {
    tuber:         { name: 'Guz ciemieniowy', latin: 'tuber parietale', palp: true, pair: true,
                     def: 'Najbardziej wypukłe miejsce kości ciemieniowej — tu czaszka jest najszersza.' },
    temporal_line: { name: 'Kresa skroniowa', latin: 'linea temporalis superior et inferior', palp: false, pair: true, line: 'temporal_line',
                     def: 'Na kości ciemieniowej podwójna: do górnej przyczepia się powięź skroniowa, do dolnej — mięsień skroniowy.' },
    coronal:       { name: 'Szew wieńcowy', latin: 'sutura coronalis', palp: false, pair: true, line: 'coronal',
                     def: 'Łączy kości ciemieniowe z kością czołową.' },
    sagittal:      { name: 'Szew strzałkowy', latin: 'sutura sagittalis', palp: false, line: 'sagittal',
                     def: 'Szew w linii środkowej między obiema kośćmi ciemieniowymi. Z przodu styka się ze szwem wieńcowym (bregma), z tyłu — z węgłowym (lambda).' },
    lambdoid:      { name: 'Szew węgłowy', latin: 'sutura lambdoidea', palp: false, pair: true, line: 'lambdoid',
                     def: 'Szew między kośćmi ciemieniowymi a kością potyliczną, w kształcie greckiej litery lambda (Λ).' },
    squamous:      { name: 'Szew łuskowy', latin: 'sutura squamosa', palp: false, pair: true, line: 'squamous',
                     def: 'Łukowaty szew między kością ciemieniową a łuską kości skroniowej. Łuska zachodzi na kość ciemieniową jak dachówka.' },
  },
  occipital: {
    protuberance:  { name: 'Guzowatość potyliczna zewnętrzna', latin: 'protuberantia occipitalis externa', palp: true,
                     def: 'Wyczuwalny guzek w linii środkowej z tyłu głowy, na granicy karku. Przyczep więzadła karkowego i mięśnia czworobocznego.' },
    nuchal_sup:    { name: 'Kresa karkowa górna', latin: 'linea nuchae superior', palp: true, pair: true,
                     def: 'Biegnie na boki od guzowatości potylicznej. Przyczep mięśni czworobocznego, płatowatego głowy i mostkowo-obojczykowo-sutkowego.' },
    squama:        { name: 'Łuska potyliczna', latin: 'squama occipitalis', palp: true,
                     def: 'Duża, wypukła tylna część kości potylicznej.' },
    foramen_magnum:{ name: 'Otwór wielki', latin: 'foramen magnum', palp: false,
                     def: 'Duży otwór w podstawie czaszki. Przechodzi przez niego rdzeń kręgowy (przejście w rdzeń przedłużony) i tętnice kręgowe.' },
    condyle:       { name: 'Kłykieć potyliczny', latin: 'condylus occipitalis', palp: false, pair: true,
                     def: 'Owalne wyniosłości po bokach otworu wielkiego. Tworzą z kręgiem szczytowym (C1) staw szczytowo-potyliczny — ruch „tak”.' },
    lambdoid:      { name: 'Szew węgłowy', latin: 'sutura lambdoidea', palp: false, pair: true, line: 'lambdoid',
                     def: 'Łączy kość potyliczną z kośćmi ciemieniowymi.' },
  },
  temporal: {
    squama:        { name: 'Łuska skroniowa', latin: 'pars squamosa', palp: false, pair: true,
                     def: 'Cienka, płaska część kości skroniowej, nad uchem. Przykrywa ją mięsień skroniowy.' },
    zyg_proc:      { name: 'Wyrostek jarzmowy', latin: 'processus zygomaticus', palp: true, pair: true,
                     def: 'Biegnie do przodu i łączy się z kością jarzmową w łuk jarzmowy — wyczuwalny przed uchem, w linii od ucha do policzka.' },
    fossa:         { name: 'Dół żuchwowy', latin: 'fossa mandibularis', palp: false, pair: true,
                     def: 'Zagłębienie przed otworem słuchowym zewnętrznym. Leży w nim głowa żuchwy — staw skroniowo-żuchwowy.' },
    meatus:        { name: 'Otwór słuchowy zewnętrzny', latin: 'porus acusticus externus', palp: true, pair: true,
                     def: 'Wejście do przewodu słuchowego zewnętrznego. Na żywym człowieku leży w głębi małżowiny usznej.' },
    mastoid:       { name: 'Wyrostek sutkowaty', latin: 'processus mastoideus', palp: true, pair: true,
                     def: 'Wyczuwalny za małżowiną uszną (nazywany też wyrostkiem sutkowym). Wewnątrz ma komórki powietrzne. Przyczep mięśni mostkowo-obojczykowo-sutkowego, płatowatego głowy i najdłuższego głowy.' },
    styloid:       { name: 'Wyrostek rylcowaty', latin: 'processus styloideus', palp: false, pair: true,
                     def: 'Cienki, ostry wyrostek skierowany w dół i do przodu, przyśrodkowo od wyrostka sutkowatego. Przyczep mięśni i więzadeł gnyku, języka i gardła.' },
    squamous:      { name: 'Szew łuskowy', latin: 'sutura squamosa', palp: false, pair: true, line: 'squamous',
                     def: 'Łączy łuskę skroniową z kością ciemieniową.' },
  },
  sphenoid: {
    greater_wing:  { name: 'Skrzydło większe', latin: 'ala major', palp: true, pair: true,
                     def: 'Widoczne z boku czaszki w skroni, za oczodołem. Tworzy część dołu skroniowego i bocznej ściany oczodołu.' },
    pterion:       { name: 'Pterion', latin: 'pterion', palp: true, pair: true,
                     def: 'Miejsce zetknięcia kości czołowej, ciemieniowej, skroniowej i skrzydła większego klinowej — w skroni, ok. 3 cm za bocznym brzegiem oczodołu i ok. 4 cm nad łukiem jarzmowym. Najcieńsza część bocznej ściany czaszki.' },
    lesser_wing:   { name: 'Skrzydło mniejsze', latin: 'ala minor', palp: false, pair: true,
                     def: 'Odchodzi od górnej części trzonu. U jego nasady leży kanał wzrokowy (nerw wzrokowy).' },
    sella:         { name: 'Siodło tureckie', latin: 'sella turcica', palp: false,
                     def: 'Zagłębienie na górnej powierzchni trzonu kości klinowej. Leży w nim przysadka mózgowa.' },
    pterygoid:     { name: 'Wyrostek skrzydłowaty', latin: 'processus pterygoideus', palp: false, pair: true,
                     def: 'Skierowany w dół, za szczęką. Przyczep mięśni skrzydłowych (żucie).' },
  },
  ethmoid: {
    crista_galli:  { name: 'Grzebień koguci', latin: 'crista galli', palp: false,
                     def: 'Wyniosłość wystająca do jamy czaszki. Przyczepia się do niej sierp mózgu.' },
    cribriform:    { name: 'Blaszka sitowa', latin: 'lamina cribrosa', palp: false,
                     def: 'Pozioma blaszka z licznymi otworkami — przechodzą przez nie nici węchowe do jamy nosowej.' },
    perpendicular: { name: 'Blaszka pionowa', latin: 'lamina perpendicularis', palp: false,
                     def: 'Górna część kostnej przegrody nosa (niżej i z tyłu — lemiesz).' },
    labyrinth:     { name: 'Błędnik sitowy', latin: 'labyrinthus ethmoidalis', palp: false, pair: true,
                     def: 'Zbiór cienkościennych komórek sitowych między oczodołem a jamą nosową. Jego blaszka oczodołowa tworzy część przyśrodkowej ściany oczodołu.' },
  },
  nasal: {
    nasion:        { name: 'Nasion', latin: 'nasion', palp: true,
                     def: 'Punkt w linii środkowej, w którym kości nosowe łączą się z kością czołową — najgłębsze miejsce u nasady nosa.' },
    nasal_dorsum:  { name: 'Grzbiet nosa (kostny)', latin: 'dorsum nasi', palp: true,
                     def: 'Kości nosowe tworzą górną, twardą część grzbietu nosa. Ich dolny brzeg łączy się z chrząstkami nosa.' },
  },
  lacrimal: {
    lacrimal_fossa:{ name: 'Dół woreczka łzowego', latin: 'fossa sacci lacrimalis', palp: false, pair: true,
                     def: 'Rowek w przyśrodkowej ścianie oczodołu (razem z wyrostkiem czołowym szczęki). Leży w nim woreczek łzowy.' },
  },
  zygomatic: {
    prominence:    { name: 'Wyniosłość jarzmowa', latin: 'facies lateralis ossis zygomatici', palp: true, pair: true,
                     def: 'Wypukła powierzchnia boczna kości jarzmowej — najwyższy punkt policzka („kość policzkowa”).' },
    temporal_proc: { name: 'Wyrostek skroniowy (łuk jarzmowy)', latin: 'processus temporalis', palp: true, pair: true,
                     def: 'Biegnie do tyłu i łączy się z wyrostkiem jarzmowym kości skroniowej — razem tworzą łuk jarzmowy. Od jego dolnego brzegu zaczyna się żwacz.' },
    frontal_proc:  { name: 'Wyrostek czołowy', latin: 'processus frontalis', palp: true, pair: true,
                     def: 'Biegnie w górę i tworzy boczny brzeg oczodołu, łącząc się z wyrostkiem jarzmowym kości czołowej.' },
  },
  maxilla: {
    frontal_proc:  { name: 'Wyrostek czołowy szczęki', latin: 'processus frontalis maxillae', palp: true, pair: true,
                     def: 'Biegnie w górę obok kości nosowej do kości czołowej. Tworzy przyśrodkowy brzeg oczodołu.' },
    infraorbital:  { name: 'Otwór podoczodołowy', latin: 'foramen infraorbitale', palp: true, pair: true,
                     def: 'Ok. 1 cm pod dolnym brzegiem oczodołu. Wychodzą przez niego nerw i naczynia podoczodołowe.' },
    zyg_proc:      { name: 'Wyrostek jarzmowy szczęki', latin: 'processus zygomaticus maxillae', palp: false, pair: true,
                     def: 'Łączy szczękę z kością jarzmową.' },
    sinus:         { name: 'Zatoka szczękowa', latin: 'sinus maxillaris', palp: false, pair: true,
                     def: 'Największa zatoka przynosowa — wypełnia trzon szczęki, pod dnem oczodołu. Uchodzi do przewodu nosowego środkowego.' },
    ans:           { name: 'Kolec nosowy przedni', latin: 'spina nasalis anterior', palp: false,
                     def: 'Ostry wyrostek w linii środkowej, u dolnego brzegu otworu gruszkowatego (wejścia do kostnej jamy nosowej).' },
    alveolar:      { name: 'Wyrostek zębodołowy', latin: 'processus alveolaris', palp: false, pair: true,
                     def: 'Dolna część szczęki z zębodołami, w których tkwią zęby górne.' },
    palatine_proc: { name: 'Wyrostek podniebienny', latin: 'processus palatinus', palp: false,
                     def: 'Pozioma blaszka — oba wyrostki tworzą przednią, większą część podniebienia twardego (dno jamy nosowej, sklepienie jamy ustnej).' },
  },
  mandible: {
    body:          { name: 'Trzon żuchwy', latin: 'corpus mandibulae', palp: true, pair: true,
                     def: 'Pozioma część żuchwy w kształcie podkowy. Jej dolny brzeg jest dobrze wyczuwalny na całej długości.' },
    ramus:         { name: 'Gałąź żuchwy', latin: 'ramus mandibulae', palp: true, pair: true,
                     def: 'Pionowa część po każdej stronie. Na jej bocznej powierzchni leży żwacz.' },
    angle:         { name: 'Kąt żuchwy', latin: 'angulus mandibulae', palp: true, pair: true,
                     def: 'Miejsce przejścia trzonu w gałąź. Przyczep żwacza (z zewnątrz) i mięśnia skrzydłowego przyśrodkowego (od wewnątrz).' },
    condyle:       { name: 'Wyrostek kłykciowy (głowa żuchwy)', latin: 'processus condylaris', palp: true, pair: true,
                     def: 'Tylny wyrostek gałęzi zakończony głową żuchwy, która w dole żuchwowym kości skroniowej tworzy staw skroniowo-żuchwowy. Wyczuwalny przed uchem przy otwieraniu ust.' },
    coronoid:      { name: 'Wyrostek dziobiasty', latin: 'processus coronoideus', palp: false, pair: true,
                     def: 'Przedni, płaski wyrostek gałęzi, chowa się pod łukiem jarzmowym. Przyczep mięśnia skroniowego.' },
    mental_foramen:{ name: 'Otwór bródkowy', latin: 'foramen mentale', palp: true, pair: true,
                     def: 'Na bocznej powierzchni trzonu, zwykle pod drugim zębem przedtrzonowym. Wychodzi przez niego nerw bródkowy.' },
    mental_prot:   { name: 'Guzowatość bródkowa', latin: 'protuberantia mentalis', palp: true,
                     def: 'Wyniosłość w linii środkowej, tworzy kostny podbródek.' },
    alveolar:      { name: 'Część zębodołowa', latin: 'pars alveolaris', palp: false,
                     def: 'Górna część trzonu z zębodołami, w których tkwią zęby dolne.' },
  },
  vomer: {
    vomer:         { name: 'Lemiesz', latin: 'vomer', palp: false,
                     def: 'Tylna i dolna część kostnej przegrody nosa.' },
  },
  palatine: {
    horizontal:    { name: 'Blaszka pozioma', latin: 'lamina horizontalis', palp: false, pair: true,
                     def: 'Tworzy tylną część podniebienia twardego, za wyrostkami podniebiennymi szczęk.' },
  },
  concha: {
    concha:        { name: 'Małżowina nosowa dolna', latin: 'concha nasalis inferior', palp: false, pair: true,
                     def: 'Zwinięta blaszka na bocznej ścianie jamy nosowej, nad przewodem nosowym dolnym.' },
  },
  teeth: {
    incisor:       { name: 'Siekacze', latin: 'dentes incisivi', palp: false, pair: true,
                     def: 'Przednie zęby o płaskiej, dłutowatej koronie — po 2 w każdej ćwiartce. Służą do odgryzania.' },
    canine:        { name: 'Kieł', latin: 'dens caninus', palp: false, pair: true,
                     def: 'Jeden w każdej ćwiartce, o najdłuższym korzeniu. Służy do rozrywania pokarmu.' },
    premolar:      { name: 'Zęby przedtrzonowe', latin: 'dentes premolares', palp: false, pair: true,
                     def: 'Po 2 w każdej ćwiartce, z dwoma guzkami na koronie.' },
    molar:         { name: 'Zęby trzonowe', latin: 'dentes molares', palp: false, pair: true,
                     def: 'Największe zęby, do rozcierania pokarmu. U dorosłego po 3 w każdej ćwiartce (trzeci — ząb mądrości — nie występuje w modelu).' },
  },
};

// Kolejność kości w menu i grupy (NC — mózgoczaszka, VC — twarzoczaszka)
export const SKULL_ORDER = ['frontal', 'parietal', 'occipital', 'temporal', 'sphenoid', 'ethmoid',
  'nasal', 'lacrimal', 'zygomatic', 'maxilla', 'mandible', 'vomer', 'palatine', 'concha', 'teeth'];
export const SKULL_GROUP = { frontal: 'NC', parietal: 'NC', occipital: 'NC', temporal: 'NC', sphenoid: 'NC', ethmoid: 'NC',
  nasal: 'VC', lacrimal: 'VC', zygomatic: 'VC', maxilla: 'VC', mandible: 'VC', vomer: 'VC', palatine: 'VC', concha: 'VC', teeth: 'VC' };
